<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Maintenance Report</title>

    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 10px;
            color: #111827;
        }

        .header {
            width: 100%;
            margin-bottom: 18px;
        }

        .header td {
            vertical-align: top;
        }

        .logo {
            height: 65px;
        }

        h1 {
            margin: 0;
            font-size: 22px;
        }

        .hotel {
            font-size: 13px;
            font-weight: bold;
            margin-top: 4px;
        }

        .meta {
            font-size: 10px;
            color: #555;
            margin-top: 3px;
        }

        .report-title {
            background: #111827;
            color: white;
            padding: 10px;
            text-align: center;
            font-size: 14px;
            font-weight: bold;
            margin-bottom: 14px;
        }

        .summary {
            width: 100%;
            margin-bottom: 18px;
            border-collapse: collapse;
        }

        .summary td {
            border: 1px solid #ddd;
            padding: 10px;
            text-align: center;
            font-weight: bold;
            background: #f3f4f6;
        }

        .jobs {
            width: 100%;
            border-collapse: collapse;
        }

        .jobs th {
            background: #111827;
            color: white;
            padding: 7px;
            text-align: left;
            font-size: 9px;
        }

        .jobs td {
            border: 1px solid #ddd;
            padding: 7px;
            font-size: 9px;
            vertical-align: top;
        }

        .footer {
            margin-top: 18px;
            border-top: 1px solid #ddd;
            padding-top: 10px;
            font-size: 10px;
            color: #555;
        }
    </style>
</head>

<body>

@php
    $totalJobs = $jobs->count();
    $pendingJobs = $jobs->where('status', 'pending')->count();
    $inProgressJobs = $jobs->where('status', 'in_progress')->count();
    $completedJobs = $jobs->where('status', 'completed')->count();
    $urgentJobs = $jobs->where('priority', 'urgent')->count();
@endphp

<table class="header">
    <tr>
        <td style="width:25%;">
            <img src="{{ public_path('myapp.png') }}" class="logo">
        </td>

        <td style="width:75%; text-align:right;">
            <h1>MGM Operations Platform</h1>
            <div class="hotel">MGM Muthu Glasgow River Hotel</div>
            <div class="meta">Report: Maintenance Report</div>
            <div class="meta">Generated By: {{ auth()->user()->name }}</div>
            <div class="meta">Generated Date: {{ now()->format('d M Y H:i') }}</div>
        </td>
    </tr>
</table>

<div class="report-title">
    Maintenance Report
</div>

<table class="summary">
    <tr>
        <td>Total Jobs<br>{{ $totalJobs }}</td>
        <td>Pending<br>{{ $pendingJobs }}</td>
        <td>In Progress<br>{{ $inProgressJobs }}</td>
        <td>Completed<br>{{ $completedJobs }}</td>
        <td>Urgent<br>{{ $urgentJobs }}</td>
    </tr>
</table>

<table class="jobs">
    <thead>
        <tr>
            <th>Date</th>
            <th>Title</th>
            <th>Location</th>
            <th>Department</th>
            <th>Reported By</th>
            <th>Assigned To</th>
            <th>Priority</th>
            <th>Status</th>
        </tr>
    </thead>

    <tbody>
        @forelse($jobs as $job)
            <tr>
                <td>{{ $job->created_at->format('d/m/Y') }}</td>

                <td>
                    <strong>{{ $job->title }}</strong><br>
                    {{ \Illuminate\Support\Str::limit($job->description, 80) }}
                </td>

                <td>
                    {{ $job->location ?? '-' }}
                    @if($job->room_number)
                        <br>Room: {{ $job->room_number }}
                    @endif
                </td>

                <td>{{ $job->department->name ?? '-' }}</td>
                <td>{{ $job->reportedBy->name ?? '-' }}</td>
                <td>{{ $job->assignedTo->name ?? '-' }}</td>
                <td>{{ ucfirst($job->priority) }}</td>
                <td>{{ ucwords(str_replace('_', ' ', $job->status)) }}</td>
            </tr>
        @empty
            <tr>
                <td colspan="8" style="text-align:center;">
                    No maintenance jobs found.
                </td>
            </tr>
        @endforelse
    </tbody>
</table>

<div class="footer">
    This report was generated by {{ auth()->user()->name }}
    from MGM Muthu Glasgow River Hotel on {{ now()->format('d/m/Y \a\t H:i') }}.
</div>

</body>
</html>