<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Restaurant Booking Report</title>

    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 10px;
            color: #111827;
        }

        .header-table {
            width: 100%;
            margin-bottom: 18px;
            border: none;
        }

        .header-table td {
            border: none;
            padding: 0;
            vertical-align: top;
        }

        .logo {
            height: 70px;
        }

        h1 {
            margin: 0;
            font-size: 22px;
        }

        .hotel-name {
            font-size: 13px;
            font-weight: bold;
            margin-top: 4px;
        }

        .meta {
            font-size: 10px;
            color: #555;
            margin-top: 3px;
        }

        .report-type-box {
            background: #111827;
            color: white;
            padding: 10px;
            margin-bottom: 14px;
            font-size: 13px;
            font-weight: bold;
            text-align: center;
            border-radius: 4px;
        }

        .summary {
            width: 100%;
            margin-bottom: 16px;
            border-collapse: collapse;
        }

        .summary td {
            padding: 10px;
            border: 1px solid #ddd;
            font-weight: bold;
            text-align: center;
            background: #f3f4f6;
        }

        .filter-info {
            margin-bottom: 12px;
            font-size: 10px;
            color: #374151;
        }

        .booking-table {
            width: 100%;
            border-collapse: collapse;
        }

        .booking-table th {
            background: #111827;
            color: white;
            padding: 7px;
            text-align: left;
            font-size: 9px;
        }

        .booking-table td {
            padding: 7px;
            border: 1px solid #ddd;
            font-size: 9px;
        }

        .footer {
            margin-top: 18px;
            font-size: 10px;
            color: #555;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
    </style>
</head>
<body>

@php
    $bookingType = request('booking_type');

    if ($bookingType === 'afternoon_tea') {
        $reportTypeLabel = 'Afternoon Tea Report';
    } elseif ($bookingType === 'dinner') {
        $reportTypeLabel = 'Dinner Report';
    } else {
        $reportTypeLabel = 'Afternoon Tea & Dinner Report';
    }
@endphp

<table class="header-table">
    <tr>
        <td style="width: 25%;">
            <img src="{{ public_path('images/mgm-logo.png') }}" class="logo">
        </td>

        <td style="width: 75%; text-align: right;">
            <h1>Restaurant Booking Report</h1>
            <div class="hotel-name">MGM Muthu Glasgow River Hotel</div>
            <div class="meta">Generated: {{ now()->format('d/m/Y') }}</div>
            <div class="meta">Generated By: {{ auth()->user()->name }}</div>
        </td>
    </tr>
</table>

<div class="report-type-box">
    {{ $reportTypeLabel }}
</div>

<div class="filter-info">
    <strong>Date From:</strong> {{ request('date_from') ?: 'All' }}
    |
    <strong>Date To:</strong> {{ request('date_to') ?: 'All' }}
    |
    <strong>Status:</strong> {{ request('status') ? ucwords(str_replace('_', ' ', request('status'))) : 'All' }}
</div>

<table class="summary">
    <tr>
        <td>Total Bookings: {{ $totalBookings }}</td>
        <td>Total Pax: {{ $totalPax }}</td>
        <td>Overbookings: {{ $overBookings }}</td>
    </tr>
</table>

<table class="booking-table">
    <thead>
        <tr>
            <th>Date</th>
            <th>Time</th>
            <th>Guest</th>
            <th>Phone</th>
            <th>Email</th>
            <th>Pax</th>
            <th>Table</th>
            <th>Status</th>
            <th>Voucher</th>
            <th>Overbooking</th>
        </tr>
    </thead>

    <tbody>
        @forelse($bookings as $booking)
            <tr>
                <td>{{ \Carbon\Carbon::parse($booking->booking_date)->format('d/m/Y') }}</td>

                <td>
                    {{ \Carbon\Carbon::parse($booking->slot_start_time)->format('g:i A') }}
                    -
                    {{ \Carbon\Carbon::parse($booking->slot_end_time)->format('g:i A') }}
                </td>

                <td>{{ $booking->guest_name }}</td>
                <td>{{ $booking->guest_phone ?? '-' }}</td>
                <td>{{ $booking->guest_email ?? '-' }}</td>
                <td>{{ $booking->pax }}</td>
                <td>{{ $booking->table->table_name ?? '-' }}</td>
                <td>{{ ucwords(str_replace('_', ' ', $booking->status)) }}</td>
                <td>{{ $booking->voucher_code ?? '-' }}</td>
                <td>{{ $booking->is_overbooking ? 'Yes' : 'No' }}</td>
            </tr>
        @empty
            <tr>
                <td colspan="10" style="text-align:center;">
                    No bookings found.
                </td>
            </tr>
        @endforelse
    </tbody>
</table>

<div class="footer">
    This report was generated by {{ auth()->user()->name }}
    from MGM Muthu Glasgow River Hotel on
    {{ now()->format('d/m/Y') }}.
</div>

</body>
</html>